version: "3"
services:
  docker-shell:
    build: .
    image: docker-shell:1.24
    container_name: docker-shell
    stdin_open: true
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "docker-shell-home:/home"
      - "docker-shell-share:/tmp/mnt"

volumes:
  docker-shell-share:
    external: true
  docker-shell-home:
    external: true

